theme: "hugo-PaperMod"
baseURL: /
languageCode: en-us
title: My New Hugo Site
menu:
      main:
        - identifier: archive
          name: Archives
          url: /archives
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: search
          name: Search
          url: /search/